### ISSUE TITLE
I need only the raw browser code

### ISSUE THREAD

**Issue by AndyOGo** [choojs/nanohtml#119]
Really awesome lib, I loved `bel` and just upgraded to `nanohtml`.

Since I bundle for the web, I don't like to include the server code too by importing it like
```js
import html from 'nanohtml'
```

I could workaround it by just importing the browser files directly by
```js
import html from 'nanohtml/lib/browser'
```

Unfortunately same does not work with `nanohtml/raw` and I rely at your project folder structure.

I could also do some magic with `rollup-plugin-replace`, but again, I would rely on your code not to change...

May I ask you to provide separate entry points for client and server scripts?

**Comment by goto-bus-stop** [comment]
If you're bundling for the web, the bundler should only look at the `browser` key and not include the server code. Is it doing something different or am I misunderstanding?

**Comment by AndyOGo** [comment]
Well I think I overcomplicated things.

Correct, you have a `browser` field but only for the `index.js`.

For `nanohtml/raw` always both server and client is bundled.

**Comment by goto-bus-stop** [comment]
> For `nanohtml/raw` always both server and client is bundled.

true. that's only about 90 bytes though, not sure if it's worth it to split them up. we want `nanohtml/raw` to do the right thing whether you're importing it on the server or the client.

**Comment by AndyOGo** [comment]
I would split it and add it to the `browser` field

**Comment by goto-bus-stop** [comment]
Oh right, I forgot for a moment that the`browser` field has an object syntax to replace individual files. That sounds fine to me. The server version will need a runtime check to import the browser version if `window` exists, to support electron. PR welcome!

**Comment by AndyOGo** [comment]
Cool, I will provide a PR. Just a give me a moment

**Comment by AndyOGo** [comment]
here you go.
I tested it by `npm run test` - all tests ok.

Thanks for being open for a change :)
