### ISSUE TITLE
How did the change from bel to nanohtml come about - I'm curious

### ISSUE THREAD

**Issue by AndyOGo** [choojs/nanohtml#126]
I would be really interested what happened that `bel` is completely deprecated and incorporated as `nanohtml` into **choojs**?

**Comment by bcomnes** [comment]
See https://github.com/choojs/nanohtml/pull/109 for some hints

**Comment by AndyOGo** [comment]
@bcomnes thank you, got it.

**Comment by goto-bus-stop** [comment]
that, and this name is similar to the other nano* modules in the choo ecosystem!
