### ISSUE TITLE
`default` alias not defined on server.js

### ISSUE THREAD

**Issue by seangenabe** [choojs/nanohtml#130]
`module.exports.default` seems to be defined in browser.js but not in server.js.

**Comment by goto-bus-stop** [comment]
Huh, i'm surprised `browser.js` sets a `default` property. i guess it'd be better if both versions do though, yea.

**Comment by josephg** [comment]
This is important because of the way the types have been set up. The types declare that nano is an `export default function` - which requires that the default property is set for it to work.

**Comment by goto-bus-stop** [comment]
Ohh, it was for typescript. That makes sense!

**Comment by goto-bus-stop** [comment]
:package: v1.2.6
