### ISSUE TITLE
autofocus on input

### ISSUE THREAD

**Issue by cy6erlion** [choojs/nanohtml#168]
Hi, thank you for creating nanohtml.

I am trying to autofocus (focus on a text input when the DOM is loaded) but it is
not working, here is my code:

```javascript
return html `
  <body>
    <input type="text" autofocus="autofocus">
  </body>
`
```
Why is it not working and how can I solve this?

**Comment by cy6erlion** [comment]
I got a work around by making the input its own component using [Nanocompnent](https://github.com/choojs/nanocomponent):

```javascript
var Nanocomponent = require('choo/component');
var html = require('choo/html');

module.exports = ScanInput;

function ScanInput() {
    if (!(this instanceof ScanInput))
        return new ScanInput(state, emit);

    Nanocomponent.call(this);
}

ScanInput.prototype = Object.create(Nanocomponent.prototype);

ScanInput.prototype.createElement = function() {
    return html `<input type="text" autofocus >`;
}

ScanInput.prototype.load = function(el) {
    el.focus();
};
```

**Comment by goto-bus-stop** [comment]
you can also use https://www.npmjs.com/package/dom-autofocus with basically does the same thing as that nanocomponent
