### ISSUE TITLE
babel + rollup import error

### ISSUE THREAD

**Issue by bennlich** [choojs/nanohtml#171]
In my main.js I have:
```
import html from 'nanohtml';
```

My .babelrc:

```
{
  "presets": [
    ["@babel/env", {"modules": false}]
  ],
  "plugins": [
    ["./node_modules/nanohtml/lib/babel.js", {
      "useImport": true
    }]
  ]
}
```

And when I try to `rollup`:
```
src/main.js: (1:7)
[!] Error: 'default' is not exported by node_modules/nanohtml/lib/append-child.js, imported by src/main.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/main.js (1:7)
1: import _appendChild from "nanohtml/lib/append-child";
          ^
```
:( Any ideas what's going on here? Seems like babel is not transforming the module.exports statement in nanohtml/lib/append-child?

Versions:
```
  "devDependencies": {
    "@babel/core": "^7.10.4",
    "@babel/preset-env": "^7.10.4",
    "@rollup/plugin-babel": "^5.0.4",
    "@rollup/plugin-node-resolve": "^8.1.0",
    "rollup": "^2.18.1",
    "sass": "^1.26.5"
  },
```

**Comment by bennlich** [comment]
I was able to import nanohtml with rollup using the [@rollup/plugin-commonjs](https://github.com/rollup/plugins/tree/master/packages/commonjs#using-with-rollupplugin-node-resolve) module.

In main.js:
```
import html from 'nanohtml/lib/browser';
```

And my .babelrc.json:

```
{
  "presets": [
    ["@babel/env", {"modules": false}]
  ]
}
```

Should I update the nanohtml readme with this method?

**Comment by goto-bus-stop** [comment]
@bennlich if you could add that to the readme that would be great!

**Comment by bennlich** [comment]
Kk! Have a look at: https://github.com/choojs/nanohtml/pull/172

**Comment by goto-bus-stop** [comment]
merged 💃
