### ISSUE TITLE
Question on upgrading from bel@5.1.7

### ISSUE THREAD

**Issue by ralphtheninja** [choojs/nanohtml#174]
Hi,

We're using `bel@5.1.7` in `mixmap` (peermaps) and just noticed that it was renamed to `nanohtml`. I'm wondering about the changes in general in this module. Has their been many improvements? Should we upgrade? I had a quick look at all the commits and I could technically dive into all the details but wanted to ask you as well.

Cheers

**Comment by goto-bus-stop** [comment]
the main difference in nanohtml 1.0.0 was just that the browserify and babel plugins were bundled into this module. I think since then there have been some bugfixes which may be useful if you write weird HTML sometimes.

**Comment by ralphtheninja** [comment]
@goto-bus-stop So it should be pretty straight forward to swap out bel for nanohtml. Thanks!
