### ISSUE TITLE
seems to ignore html attibutes without assigment

### ISSUE THREAD

**Issue by toddself** [choojs/nanohtml#28]
`<input disabled><br>`

returns

`<input><br></input>`

but

`<input disabled="true"><br>`

returns

`<input disabled=disabled><br>`

Is this intentional? Un-assigned attributes like the first example are valid in HTML5 (I believe actually valid in everything except XHTML)

(ie the following is valid according to [https://validator.w3.org](https://validator.w3.org)

``` html
<!doctype html>
<title>test</title>
<form>
<input disabled>
</form>
```

)

**Comment by toddself** [comment]
nope using it wrong :)

**Comment by jmeas** [comment]
Likely related: https://github.com/substack/hyperx/issues/14

**Comment by toddself** [comment]
Yeah, looks totally related.

Thanks for the heads up.  I'll follow that issue :)

**Comment by roobie** [comment]
@yoshuawuyts isn't this what e.g. https://github.com/yoshuawuyts/cache-element/ solves?

**Comment by goto-bus-stop** [comment]
appears to work on master. thanks!

```js
console.log(html`<p><input disabled><br></p>`.outerHTML)
// <p><input disabled="disabled"><br></p>
```
