### ISSUE TITLE
<label> around an input field eats following elements

### ISSUE THREAD

**Issue by josephg** [choojs/nanohtml#34]
I'm not sure what the problem is, but if I have an input field inside a label [as recommended by mdn](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox):

``` html
bel(`<div>
  <label> <input type="checkbox" checked> text </label>
  <a>outside</a>
</div>`).toString();

// ->
<div>
  <label> <input type="text" type="type" checkbox"="checkbox&quot;" />
    <a>outside</a>
  </label>
</div>
```

... The following elements somehow teleport _inside_ the label.

> [Edited: Added `checked` to the input tag, which is required to reproduce the bug.]

**Comment by jmeas** [comment]
Can you make a requirebin? [This seems to work for me](http://requirebin.com/?gist=09b0facfd46609d6767d66d35600eeae).

**Comment by josephg** [comment]
Oops! I was a bit too keen at trimming down the test case. Requirebin only works in incognito windows for some reason for me, where I'm not logged in to github. (That or it takes 20+ seconds to start up, in which case I'm just not patient enough.)

Anyway:

![image](https://cloud.githubusercontent.com/assets/47413/16361175/5197fbdc-3bca-11e6-8270-509ee5ddeaef.png)

```javascript
var bel = require('bel');

var html = bel`<div>
  <label>
  	<input type="checkbox" id="keep" checked>text
  </label>
  <a>Outside</a>
</div>`;
  
console.log('hello', html);
```

Cases:

- `<input type="checkbox" id="keep" checked>`: **buggy**
- `<input type="checkbox" id="keep" checked=true>`: **buggy**
- `<input type="checkbox" id="keep" checked="true">`: *ok*
- `<input type="checkbox" id="keep" checked />`: *ok*

**Comment by yoshuawuyts** [comment]
Probably related to https://github.com/shama/bel/issues/28

**Comment by jmeas** [comment]
Ah, oops, somehow the checked attr got removed when I was playing around in Requirebin, and I didn't notice.

Thanks for taking the time to make that Requirebin, even though it sounded pretty tedious to set up :P The two issues do seem likely to be related – thanks @yoshuawuyts !

**Comment by shama** [comment]
I'll look into this again soon. That and `<br/>` doesn't work but `<br />` does!

**Comment by goto-bus-stop** [comment]
This appears to be fixed in the latest hyperx; probably by https://github.com/choojs/hyperx/commit/d85b56b275466b920f24a0fdbc81017c4a52755c. thanks!
