### ISSUE TITLE
belCreateElement TypeError in Safari

### ISSUE THREAD

**Issue by jondashkyle** [choojs/nanohtml#39]
Running into an error with `onload` and `onunload` events in Safari. Can verify when removing the load attributes from the element the error is suppressed.

```
TypeError: Function.caller used to retrieve strict caller
```

Here is a temp URL:
http://ec2-54-201-45-223.us-west-2.compute.amazonaws.com

**Comment by shama** [comment]
I recommend using [yo-yoify](https://github.com/shama/yo-yoify) which will transform any `Function.caller` into plain strings until an alternative solution to identify element creators is implemented.

**Comment by jondashkyle** [comment]
Nice! Worth noting that I was unable to get it functioning as instructed using a `-g` global transform, but using a `-t` generic transform works a charm. Def appreciate all the work you’ve put into this!

**Comment by timkendall** [comment]
This is a weird-ass bug lol. Anyways, I can't seem to get this to work with the `babelify` transform (es2015 preset).

**Comment by fczuardi** [comment]
Not sure if I should file a different bug for this, but on firefox, using choo I get this error
```
TypeError: access to strict mode caller function is censored
```

When using a view with onload, such as:

```javascript
const mainView = (state, prev, send) => html`
<div onload=${(el) => send('bodyLoaded', el)}></div>
`;
```

Using yo-yoify didn't helped :(

**Comment by MelleB** [comment]
Woops, read over this issue... Opened a issue for the same error in Firefox hover here: #44

**Comment by josephluck** [comment]
Just seen the same error in latest Chrome (55.0.2883.95) - removing plugins using use-strict (es2015 plugin) from babel fixed it.

**Comment by josephluck** [comment]
On further inspection, yo-yoify doesn't fix the issue in safari. As far as I can see it occurs when having nested onload methods.

**Comment by harrygr** [comment]
An interim fix is to use the `es2015-nostrict`babel preset instead of the normal `es2015` one, or a preset that doesn't enforce strict mode.

**Comment by goto-bus-stop** [comment]
this is no longer an issue in nanohtml because it doesn't include `on-load` anymore.
