### ISSUE TITLE
Bug in Firefox "TypeError: access to strict mode ..."

### ISSUE THREAD

**Issue by MelleB** [choojs/nanohtml#44]
Hi,

I'm getting the following error when trying to add an onload handler to a nested element. 

```
TypeError: access to strict mode caller function is censored
```

Is this expected behavior? The line triggering this error seems to be https://github.com/shama/bel/blob/master/index.js#L68
Tested on Ubuntu / Firefox 48.0
Seems to work fine on Ubuntu / Google Chrome 52.0.2743.116 (64-bit)

Below is a minimal example reproducing the error. 

``` javascript
import bel from 'bel'

const renderObj = ({name, x, y}) => {
    return bel `<g transform="translate(${x}, ${y})" class="task" onload=${e => console.log(e) }>
      <rect width=100 height=100 />
      <text>${name}</text>
    </g>`
}


const objs = [
    {name:'foo', x:100, y:100}
];


const svg = bel`<svg onclick=${onclick}>
    ${objs.map(t => renderObj(t))}
</svg>`

document.appendChild(svg);
```

Kind regards,
Melle

**Comment by YerkoPalma** [comment]
I don't think is firefox related. Look [here](https://github.com/mantoni/choo-test/issues/1) I've faced the same error, and it was because, in my case, `babelify` introduced a `'use strict'` statement, for some reason that throw the exception you are getting. A workaround is to remove any `'use strict'` statement. In my case, I replaced babelify transform for es2040 transform. Hope it helps

**Comment by MelleB** [comment]
@YerkoPalma You might be right: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee

Switching babel with es2040 isn't really an option for me. For now I continue dev in Chrome only.

**Comment by kareniel** [comment]
Thanks so much so for the tip!

Had the same issue here. Website would work every where except on iPhone devices.
`Function.caller used to retrieve strict caller` on line 68
`belCreateElement.caller.caller.caller)`
I had at least 5 'use strict' declaration in my `bundle.js`.
Removed them all, reuploaded and everything started working.

Would love to contribute fixing it at the library level, but not sure where to start.

**Comment by shama** [comment]
Please see https://github.com/shama/bel/issues/39#issuecomment-232776543

**Comment by YerkoPalma** [comment]
I finally choose to use the `yo-yoify` option and it worked perfectly for me.

**Comment by goto-bus-stop** [comment]
this is no longer an issue in nanohtml because it doesn't include `on-load` anymore.
