### ISSUE TITLE
Invalid rendering with missing close

### ISSUE THREAD

**Issue by emilbayes** [choojs/nanohtml#54]
First I thought it was a bug in `hyperx`, but `virtual-dom` actually `throw`, so that leads me to `bel` being the issue.

The following code renders incorrectly (as I said, `virtual-dom` throws an error):

``` js
bel`<div><p>Hello World<p></div>`.toString() // => '<div>pHello World<p></p></div>'
```

Notice the `p` prepended to `Hello World`.

I'll leave this here until I need to fix it, unless someone gets to it before me 😅

**Comment by shama** [comment]
Sounds like an issue with [min-document](https://www.npmjs.com/package/min-document). On the server, that library gets used to serialize the HTML.

**Comment by goto-bus-stop** [comment]
server side rendering now works with string concatenation so this is no longer happening. thanks!
