### ISSUE TITLE
Encoded HTML ssr/browser rendering

### ISSUE THREAD

**Issue by jondashkyle** [choojs/nanohtml#84]
Really enjoying the new SSR capabilities with bel! I wanted to render some Markdown output on the server recently, and with @yoshuawuyts’s help was able to get this working in both the browser and SSR by doing something like this:

```js
var example = format('<p>some example</p><h2>markdown output</h2>')

function format (str) {
  if (typeof window !== 'undefined') {
    var wrapper = html`<div></div>`
    wrapper.innerHTML = str
    return wrapper
  } else {
    var wrapper = new String(str)
    wrapper.__encoded = true
    return wrapper
  }
}
```

And a little interactive [example using Glitch](https://glitch.com/edit/#!/wealthy-polish-1?path=app.js:20:0). Super awesome, but a little verbose. Maybe there is a way to do this using a single unified method? #42

**Comment by louiscenter** [comment]
this is a really useful snippet! thanks for sharing ✨

just incase anyone takes this for a spin with `choo`, make sure you're using `v6`, as it won't be compatible with `choo v5` (found this out the hard way 😅)

**Comment by axelav** [comment]
brilliant! spent a while digging into this issue tonight until I got down to pelo & saw what was happening. this works perfectly, should def go on the working with html section of the wiki :)

**Comment by bcomnes** [comment]
Would this be worth exporting as a bundled-but-separate utility function?

**Comment by yoshuawuyts** [comment]
Yeah, think so - something like `require('bel/unescape')` or `bel/raw`
might make sense I think. Having it be a completely separate module might
make it trickier to find / adds more deps to projects which is not great

**Comment by jondashkyle** [comment]
@yoshuawuyts Yeah, echoing that thought—was discussing this with @louiscenter as I’m using this method within several projects right now. Keeping it within the bel package but separate from the core would be a great move. I could make a PR for it?

Also, pretty fan of `bel/raw`. 3/3.

**Comment by yoshuawuyts** [comment]
Think we all agree then. PR would be grand!

**Comment by goto-bus-stop** [comment]
https://github.com/choojs/nanohtml/blob/master/raw.js !
